name: non-handed-slip-monitor

on:
  workflow_dispatch:
    inputs:
      force:
        description: Ignore timestamp and force update
        required: false
        default: ''
  # schedule:
  #   - cron:  '0 13 * * *'
      

jobs:
  track:
    name: Checks for non handed slip

    # runs-on: ubuntu-latest
    runs-on: alpine:latest 
    steps:
      - name: Check for non handed slip
        run: |
            curl -s -G 'https://e-uslugi.mvr.bg/api/Obligations/AND' \
            -d mode=1 \
            -d obligedPersonIdent=${{ secrets.OBLIGED_PERSON_IDENT }} \
            -d drivingLicenceNumber=${{ secrets.DRIVING_LICENCE_NUMBER }} \
             | jq -e 'select(.hasNonHandedSlip == false) | any'
